from flask import Blueprint, request, jsonify
from services.ai_service import ai_service_instance
from models.prompt import Prompt
from flask_jwt_extended import jwt_required, get_jwt_identity

generate_bp = Blueprint("generate_bp", __name__)

@generate_bp.route("/", methods=["POST"])
@jwt_required(optional=True)
def generate_prompt():
    data = request.get_json()
    idea = data.get("idea")

    if not idea:
        return jsonify({"status": "error", "message": "Missing idea parameter"}), 400

    try:
        generated_content = ai_service_instance.generate_and_categorize(idea)
        current_user_email = get_jwt_identity()

        if current_user_email:
            # User is logged in, save to Firebase
            prompt = Prompt.create(
                user_id=current_user_email,
                user_input=idea,
                generated_prompt=generated_content["prompt"],
                category=generated_content["category"]
            )
            # Return ID generated by Firebase along with the prompt data
            return jsonify({
                "status": "success", 
                "data": {
                    "id": prompt.id, # Firebase document ID
                    **prompt.to_dict()
                }
            }), 200
        else:
            # Guest user, return data without saving to DB
            # Frontend will handle local storage for guest users
            return jsonify({"status": "success", "data": {
                "user_input": idea,
                "generated_prompt": generated_content["prompt"],
                "category": generated_content["category"]
            }}), 200

    except Exception as e:
        import traceback
        print(traceback.format_exc()) # Log it on Vercel
        return jsonify({"status": "error", "message": f"Internal Error: {str(e)}"}), 500


